apiVersion: v1
kind: Pod
metadata:
  name: pod-privileged
  namespace: audit-zone
  labels:
    app: pod-privileged
spec:
  containers:
    - name: nginx
      image: nginx:1.27-alpine
      securityContext:
        privileged: true

