apiVersion: v1
kind: Pod
metadata:
  name: pod-hostpath
  namespace: audit-zone
  labels:
    app: pod-hostpath
spec:
  containers:
    - name: nginx
      image: nginx:1.27-alpine
      volumeMounts:
        - name: host-root
          mountPath: /host
          readOnly: true
  volumes:
    - name: host-root
      hostPath:
        path: /
        type: Directory

